# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP')),
                ('is_physical', models.BooleanField(db_index=True, default=False, help_text='True if IP is tied to hardware ; False if failover type', verbose_name='is physical')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
            ],
            options={
                'ordering': ('ip', 'is_physical'),
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('configuration', models.TextField(blank=True, verbose_name='configuration')),
                ('customer', models.CharField(db_index=True, max_length=30, verbose_name='customer')),
                ('environment', models.CharField(db_index=True, max_length=20, verbose_name='environment')),
                ('group', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='group')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('machine_lifecycle', models.CharField(choices=[(b'nonexistent', 'nonexistent'), (b'creating', 'hosting service provider creates machine'), (b'created', 'empty machine created'), (b'installing', 'OS being installed'), (b'installed', 'OS installed'), (b'provisioning', 'provisioning'), (b'provisioned', 'provisioned'), (b'removing', 'machine being removed'), (b'removed', 'machine removed')], db_index=True, max_length=20, verbose_name='lifecycle')),
                ('machine_name', models.CharField(max_length=100, unique=True, verbose_name='machine name')),
                ('machine_product', models.CharField(blank=True, help_text='Commercial product model, from hosting.', max_length=100, verbose_name='machine product')),
                ('machine_type', models.CharField(choices=[(b'vm', 'virtual machine'), (b'physical', 'physical machine')], db_index=True, max_length=20, verbose_name='type')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('os', models.CharField(blank=True, help_text='Operating system.', max_length=50, verbose_name='OS')),
                ('role', models.CharField(max_length=30, verbose_name='role')),
                ('state', models.CharField(choices=[(b'unavailable', 'nonexistent'), (b'normal', 'normal'), (b'warning', 'warning'), (b'error', 'error')], db_index=True, max_length=20, verbose_name='state')),
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, unique=True)),
            ],
            options={
                'ordering': ('customer', 'environment', 'group', 'role', 'name'),
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='inventory.Machine'),
        ),
    ]
